news_sites:
  elcolombiano:
    url: https://www.elcolombiano.com
    queries:
      homepage_article_links : '.right a'
      article_body: '.noticia'
      article_title: '.information-noticia h3'
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links : '.title-container a'
      article_body: '.modulos'
      article_title: '.titulo-principal-bk h1'
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: ''
      article_body: ''
      article_title: ''