news_sites:
  elcolombiano:
    url: https://www.elcolombiano.com
    queries:
      homepage_article_links : '.noticia-segundaria a'
      article_body: '.noticia'
      article_title: '.information-noticia h3'
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links : '.title-container a'
      article_body: '.modulos'
      article_title: '.titulo-principal-bk h1'
